name: StackableItems
author: haveric
main: haveric.stackableItems.StackableItems
version: 0.8.6.t2
dev-url: http://dev.bukkit.org/server-mods/stackableitems/
softdepend: [Vault]
commands:
    stackableitems:
        aliases: [si]
        description: Allows you to change any item's max stack amount.
        usage: