name: StackableItems
author: haveric
main: haveric.stackableItems.StackableItems
version: 0.7.5.t4
dev-url: http://dev.bukkit.org/server-mods/stackableitems/
softdepend: [Vault]
commands:
    stackableitems:
        description: Allows you to change the amount that items will stack.
        usage: