name: StackableItems
author: haveric
main: haveric.stackableItems.StackableItems
version: 0.9.2
dev-url: http://dev.bukkit.org/server-mods/stackableitems/
softdepend: [Vault]
commands:
    stackableitems:
        aliases: [si]
        description: Allows you to change any item's max stack amount.
        usage:
        
permissions:
    stackableitems.*:
        description: Gives access to all StackableItems Commands
        children:
            stackableitems.stack: true
            stackableitems.adjust: true
    stackableitems.stack:
        description: Allows a permission group to stack items.
        default: false
    stackableitems.adjust:
        description: Allows you to adjust stack configs.
        default: false