name: StackableItems
author: haveric
main: haveric.stackableItems.StackableItems
version: 0.8.3.t1
dev-url: http://dev.bukkit.org/server-mods/stackableitems/
softdepend: [Vault]
commands:
    stackableitems:
        description: Allows you to change an item's max stack amount.
        usage: