name: StackableItems
author: haveric
main: haveric.stackableItems.StackableItems
version: 0.6.4
dev-url: http://dev.bukkit.org/server-mods/stackableitems/
commands:
  stackableitems:
    description: Allows you to change the amount that items will stack.
    usage: